[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install chromium", "npm run build"]

[start]
cmd = "PLAYWRIGHT_BROWSERS_PATH=0 npm run start"
